routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

date_default_timezone_set('America/Vancouver');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('restricted', function () {
    return view('restricted');
})->name('restricted');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/toc', function(){
    return view('frontend.toc-datacore');
})->name('toc');

Route::get('/development', function(){
    return view('development');
})->name('development');

/////////////////////////////////////////////////////////////////////
// Backend
////////////////////////////////////////////////////////////////////
Route::prefix('/coreui')->name('coreui.')->group(function () {
    // Dashboard
    Route::get('/', 'HomeController@index')->name('dashboard');
    // Stats
    Route::get('statistics',function(){
        return view('backend.stats.index');
    })->name('stats')->middleware('auth')->middleware('permission:statistics.read');
    // Integrations
    Route::get('integrations',function(){
        return view('backend.integrations.index');
    })->name('integrations')->middleware('auth');

    Route::get('integrations/banner_message', 'IntegrationController@bannerIndex')->name('banner-message')->middleware('auth')->middleware('permission:banner.read');

    // Employees
    Route::get('/employees', 'EmployeeController@index')->name('employees')->middleware('permission:employee.read');
    Route::get('/employees/create', 'EmployeeController@create')->name('employees.create')->middleware('permission:employee.create');
    Route::post('/employees', 'EmployeeController@store')->name('employees.store')->middleware('permission:employee.create');
    Route::get('/employees/edit/{employee}', 'EmployeeController@edit')->name('employees.edit')->middleware('permission:employee.update');
    Route::patch('/employees/edit/{employee}', 'EmployeeController@update')->name('employees.update')->middleware('permission:employee.update');
    Route::patch('/employees/activate/{employee}', 'EmployeeController@activate')->name('employees.activate')->middleware('permission:employee.update');
    Route::patch('/employees/deactivate/{employee}', 'EmployeeController@deactivate')->name('employees.deactivate')->middleware('permission:employee.update');
    Route::get('/employees/delete/{employee}', 'EmployeeController@destroy')->name('employees.delete')->middleware('permission:employee.delete');
    Route::get('/employees/{employee}/shift','EmployeeController@shifts')->name('employees.shifts')->middleware('permission:employee.update');
    
    // Profile
    Route::get('/profile', 'EmployeeController@profile')->name('profile')->middleware('auth');
    Route::patch('/profile/{employee}', 'EmployeeController@profile_update')->name('profile.update')->middleware('auth');
    
    //Employee Permissions
    Route::get('/employees/{employee}/permissions', 'EmployeePermissionController@edit')->name('employee-permission.edit')->middleware('permission:employee.update');
    Route::patch('/employees/{employee}/permissions', 'EmployeePermissionController@update')->name('employee-permission.update')->middleware('permission:employee.update');

    // Employee Roles
    Route::get('/roles', 'EmployeeRoleController@index')->name('employee-role')->middleware('permission:employee_role.read');
    Route::post('/roles', 'EmployeeRoleController@store')->name('employee-role.store')->middleware('permission:employee_role.create');
    Route::post('/roles/{employee_role}', 'EmployeeRoleController@update')->name('employee-role.update')->middleware('permission:employee_role.update');

    // Employee Role Permissions
    Route::get('/roles/{employee_role}/permissions', 'EmployeeRolePermissionController@edit')->name('employee-role-permission.edit')->middleware('permission:employee_role.update');
    Route::patch('/roles/{employee_role}/permissions', 'EmployeeRolePermissionController@update')->name('employee-role-permission.update')->middleware('permission:employee_role.update');

    // Permissions
    Route::get('/permissions', 'PermissionController@index')->name('permission')->middleware('permission:permission.read')->middleware('role:SuperAdmin');
    Route::post('/permissions', 'PermissionController@store')->name('permission.store')->middleware('permission:permission.create')->middleware('role:SuperAdmin');

    // Sales History

    Route::get('/sales_history/index', 'SalesHistoryController@index')
    ->name('sales-history')->middleware('role:SuperAdmin')->middleware('permission:sales_history.read');

    Route::get('/sales_history/upload', 'SalesHistoryController@upload')
    ->name('sales-history.upload')->middleware('permission:sales_history.create');

    Route::post('/sales_history', 'SalesHistoryController@store')
    ->name('sales-history.store')->middleware('permission:sales_history.create');

    Route::get('/sales_history/{product}', 'SalesHistoryController@show')
    ->name('sales-history.show')->middleware('role:SuperAdmin')->middleware('permission:sales_history.read');

    // Vendors

    Route::get('/vendors/index', 'VendorController@index')
    ->name('vendors')->middleware('permission:vendors.read');

    Route::get('/vendors/{vendor}/products', 'VendorController@products')
    ->name('vendors.products')->middleware('permission:vendors.read');

    Route::get('/vendors/upload', 'VendorController@upload')
    ->name('vendors.upload')->middleware('role:SuperAdmin')->middleware('permission:vendors.create');

    Route::post('/vendors', 'VendorController@store')
    ->name('vendors.store')->middleware('role:SuperAdmin')->middleware('permission:vendors.create');

    // Purchase Orders

    Route::get('/purchases/index', 'PurchaseOrderController@index')
    ->name('po')->middleware('permission:purchase_orders.read');

    Route::get('/purchases/upload', 'PurchaseOrderController@upload')
    ->name('po.upload')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    Route::post('/purchases', 'PurchaseOrderController@store')
    ->name('po.store')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    Route::get('/purchases/{po_id}', 'PurchaseOrderController@products')
    ->name('po.products')->middleware('permission:purchase_orders.read');

    Route::get('/purchases/product/upload', 'PurchaseOrderProductController@upload')
    ->name('po-product.upload')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    Route::post('/purchase_products', 'PurchaseOrderProductController@store')
    ->name('po-product.store')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    // Payroll
    Route::get('/payroll-report', 'PayrollController@index')->name('payroll')->middleware('auth');

    // Work Shifts
    Route::get('/shifts','WorkShiftController@index')->name('work-shifts')->middleware('permission:work_shifts.read');

    // Employee Shift
    Route::post('employee/shift/add','WorkShiftController@addEmployeeShift')->name('employee-shift.create')->middleware('permission:work_shifts.create');
    Route::post('employee/shift/delete','WorkShiftController@removeEmployeeShift')->name('employee-shift.delete')->middleware('permission:work_shifts.delete');

    // Settings
    Route::get('settings',function(){
        return view('backend.settings.index');
    })->name('settings')->middleware('auth');

    // Order Statuses
    Route::get('/order_statuses','OrderStatusController@index')->name('order-status')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.read');
    Route::get('/order_statuses/create','OrderStatusController@create')->name('order-status.create')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.create');
    Route::post('/order_statuses','OrderStatusController@store')->name('order-status.store')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.create');
    Route::patch('/order_statuses/edit/{orderStatus}','OrderStatusController@update')->name('order-status.update')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.update');
    Route::get('/order_statuses/delete/{orderStatus}','OrderStatusController@destroy')->name('order-status.delete')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.delete');

    // Events/Schedule
    Route::get('/schedule-vue','EventController@vue')->name('schedule-vue');
    Route::get('/schedule','EventController@index')->name('schedule');
    Route::get('/schedule-admin','EventController@admin')->name('schedule-admin')->middleware('permission:events.read');
    Route::get('/schedule-employee/{employee}','EventController@employee')->name('schedule-employee')->middleware('permission:events.read');
    Route::post('/schedule/create','EventController@create')->name('event.create');
    Route::patch('/schedule/update','EventController@update')->name('event.update');
    Route::post('/schedule/delete','EventController@destroy')->name('event.delete');


});

////////////////////////////////////////////////////////////////////////////
// Frontend
///////////////////////////////////////////////////////////////////////////

/**************************************************************
 * 
 *   Search
 * 
 ***************************************************************/ 

Route::get('/search', 'ProductController@search')->name('search');

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\EmployeeRole;
use App\Permission;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {   
        $employees = Employee::all();

        return view('backend.employees.index',compact('employees'));
    }

    public function create()
    {
        $roles = EmployeeRole::all();

        return view('backend.employees.create',compact('roles'));
    }

    public function store(Request $request)
    {   
        // Validate form
        $this->validate(request(), [
            'name' => 'required',
            'username' => 'required|string|max:255|unique:employees',
            'role' => 'required|integer',
            'email' => 'required|email|unique:employees',
            'password' => 'required|confirmed'
        ]);

        // create employee

        $employee = Employee::create([
                'name' => request('name'),
                'username' => strtolower(request('username')),
                'email' => request('email'),
                'password' => bcrypt(request('password')),
                'employee_role_id' => (int)request('role')
            ]
        );

        foreach($employee->role->permissions as $permission){
            $employee->permissions()->attach($permission->id, [
                'create' => $permission->pivot->create,
                'read' => $permission->pivot->read,
                'update' => $permission->pivot->update,
                'delete' => $permission->pivot->delete,
                ]);
        }

        $employee->save();

        session()->flash('message','You have successfully created an account for ' . $employee->name . '. Please update the permissions.');

        return redirect()->route('coreui.employee-permission.edit',$employee->id);
    }

    public function show($id)
    {
        //
    }

    public function edit(Employee $employee)
    {   
        $current = \Auth::user();
        if($employee->id!=$current->id){
            if(!$current->hasRole("SuperAdmin")){
                session()->flash('message','The page you tried to reach is restricted');
                return redirect()->route('coreui.dashboard');
            }
        }
        $roles = EmployeeRole::all();
        return view('backend.employees.edit', compact('employee','roles'));
    }

    public function update(Request $request, Employee $employee)
    {   
        $current = \Auth::user();
        if($employee->id!=$current->id){
            if(!$current->hasRole("SuperAdmin")){
                session()->flash('message','The page you tried to reach is restricted');
                return redirect()->route('coreui.dashboard');
            }
        }

        // Validate form
        $this->validate(request(), [
            'name' => 'required',
            'role' => 'required|integer',
            'password' => 'confirmed'
        ]);

        $employee->name = $request->name;
        $employee->employee_role_id = $request->role;
        if($request->password){
            $employee->password = bcrypt($request->password);
        }
        $employee->save();

        if($current->hasRole("SuperAdmin")){
            session()->flash('message','You have successfully updated ' . $employee->name);
            return redirect()->route('coreui.employees');
        }else{
            session()->flash('message','You have successfully updated your account.');
            return redirect()->route('coreui.dashboard');
        }
        
    }

    public function destroy(Employee $employee)
    {
        $employee->delete();
        session()->flash('message','You have successfully deleted ' . $employee->name .'.');
        return redirect()->route('coreui.employees');
    }

    public function deactivate(Employee $employee)
    {
        $employee->isActive = false;
        $employee->save();
        session()->flash('message','You have successfully deactivated ' . $employee->name .'.');
        return redirect()->route('coreui.employees');
    }

    public function activate(Employee $employee) {
        $employee->isActive = true;
        $employee->save();
        session()->flash('message','You have successfully activated ' . $employee->name .'.');
        return redirect()->route('coreui.employees');
    }

    public function profile(Employee $employee){
        return view('backend.employees.profile.index',compact('employee'));
    }

    public function profile_update(Request $request, Employee $employee){
        // Validate form
        $this->validate(request(), [
            'name' => 'required',
            'password' => 'confirmed'
        ]);

        $employee->name = $request->name;

        if($request->password){
            $employee->password = bcrypt($request->password);
        }
        $employee->save();

        session()->flash('message','You have successfully updated your account.');
        
        return redirect()->route('coreui.dashboard');
    }

    public function shifts(Employee $employee){
        return view('backend.employees.shifts',compact('employee'));
    }
}

resources/views/backend/employees/create.blade.php
@extends('backend.layouts.main')

@section('content')

<h1 class="mt-2">Add New Employee</h1>
<form method="POST" action="{{route('coreui.employees.store')}}" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Employee's Full Name" value="{{old('name')}}" required>
    </div>

    <div class="form-group">
        <label for="username">Username</label>
        <input type="username" class="form-control" id="username" name="username" placeholder="Enter Username" value="{{old('username')}}" required>
    </div>

    <div class="form-group">
        <label for="role">Employee Role</label>
        <select id="role" class="form-control" name="role" value="{{old('role')}}" required>
            <option value="" disabled selected>Select Role ...</option>
            @foreach ($roles as $role)
                <option value="{{$role->id}}" @if(old('role') == $role->id) selected @endif>{{$role->name}}</option>
            @endforeach
        </select>
    </div>

<div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email" value="{{old('email')}}" required>
</div>
<div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password" name="password" required>
    <small id="passHelp" class="form-text text-muted">Password must be at least 6 characters long.</small>
</div>
<div class="form-group">
    <label for="password_confirmation">Confirm Password</label>
    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Confirm Password" required>
</div>

{{-- <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Is this user active?</label>
</div>  --}}

<button type="submit" class="btn btn-primary">Submit</button>

@include('layouts.errors')

</form>


@endsection

resources/views/backend/employees/edit.blade.php
@extends('backend.layouts.main')

@section('content')
<h1 class="mt-2">Update Employee</h1>
<form method="POST" action="{{ route('coreui.employees.update',$employee->id) }}" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PATCH">
        {{ csrf_field() }}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Employee's Full Name"  value="{{$employee->name}}">
    </div>

    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Username"  value="{{$employee->username}}" disabled>
    </div>

    <div class="form-group">
        <label for="role">Employee Role</label>
        <select id="role" class="form-control" name="role">
            <option value="" disabled selected>Select Role ...</option>
            @foreach ($roles as $role)
                <option value="{{$role->id}}" @if($role->id == $employee->role->id) selected @endif>{{$role->name}}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="username">Card ID</label>
        <input type="text" class="form-control" id="cardid" name="cardid" placeholder="Card UID"  value="{{$employee->card_id}}" disabled>
    </div>

<div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ $employee->email }}" disabled>
</div>
<div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password" name="password" >
    <small id="passHelp" class="form-text text-muted">*Leave password blank if you do not want to change it.</small>
</div>
<div class="form-group">
    <label for="password_confirmation">Confirm Password</label>
    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Confirm Password">
</div>

{{-- <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Is this user active?</label>
</div>  --}}

<button type="submit" class="btn btn-primary">Update Employee</button>

@include('layouts.errors')

</form>


@endsection

resources/views/backend/employees/index.blade.php
@extends('backend.layouts.main')

@include('layouts.datatables')

@section('content')
    <h1>Employees</h1>
    @if(Auth::user()->hasAccess('employee')->create)
    <div class="d-flex flex-row-reverse pt-3 pb-2 mb-3">
        <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{route('coreui.employees.create')}}"><button class="btn btn-xs btn-primary" >Add Employee</button></a>
        </div>
        </div>
    </div>
    @endif
    <div class="table-responsive">
    <table id="employee_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
            <th class="th-sm">ID
            </th>
            <th class="th-sm">Username
            </th>
            <th class="th-sm">Name
            </th>
            <th class="th-sm">Email
            </th>
            <th class="th-sm">Role
            </th>
            <th class="th-sm">Start date
            </th>
            <th class="th-sm">Active
            </th>
            @if(Auth::user()->hasAccess('employee')->update || Auth::user()->hasAccess('employee')->delete)
            <th class="sorting_disabled">Action
            </th>
            @endif
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employee)
                <tr>
                    <td>{{$employee->id}}</td>
                    <td>{{$employee->username}}</td>
                    <td>{{$employee->name}}</td>
                    <td>{{$employee->email}}</td>
                    <td>{{$employee->role->name}}</td>
                    <td>{{$employee->created_at->toDateString()}}</td>
                    <td>@if($employee->isActive) Yes @else No @endif</td>
                    @if(Auth::user()->hasAccess('employee')->update || Auth::user()->hasAccess('employee')->delete)
                    <td style="text-align:center">
                        @if(Auth::user()->hasAccess('employee')->update)
                            <a href="{{route('coreui.employees.edit',$employee->id)}}"><button class="btn btn-sm btn-primary mb-2">Edit</button></a>
                            <a href="{{route('coreui.employee-permission.edit',$employee->id)}}"><button class="btn btn-sm btn-warning mb-2">Permissions</button></a>
                        @endif

                        @if(Auth::user()->hasAccess('work_shifts')->update && $employee->isActive && !$employee->ignoreShift() && $employee->role->id != 5)
                            <a href="{{route('coreui.employees.shifts',$employee->id)}}"><button class="btn btn-sm btn-light mb-2">Shift</button></a>
                        @endif

                        @if(Auth::user()->hasAccess('employee')->delete && $employee->role->id != 1)
                            @if($employee->isActive)
                            <div>
                            <button class="btn btn-sm btn-danger mb-2" 
                                data-toggle="modal" 
                                data-target="#deleteModal" 
                                data-id="{{ $employee->id }}" 
                                data-name="{{ $employee->name }}"
                                data-delete_url="{{ route('coreui.employees.deactivate',$employee->id) }}">Deactivate</button>
                            </div>
                            @else
                            <form action="{{ route('coreui.employees.activate',$employee->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('PATCH') }}
                                <button class="btn btn-sm btn-success mb-2">Activate</button>
                            </form>
                            @endif
                        @endif
                    </td>
                    @endif
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
      
{{-- Delete Modal --}}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Deactivate User?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Are you sure you want to deactivate <span id="employee-name"> Name </span>?
        </div>
        <div class="modal-footer">
            <form id="deactivate-form" method="POST">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger">Deactivate Employee</button>
            </form>
        </div>
        </div>
    </div>
</div>
     
@endsection

@push('bottom-scripts')
<script type="text/javascript">
    $(document).ready(function () {
        $('#employee_table').DataTable({
            "language": {
                "search": "Filter records:"
            }
            @if(Auth::user()->hasAccess('employee')->update || Auth::user()->hasAccess('employee')->delete)
            columnDefs: [ { orderable: false, targets: [6] } ]
            @endif
        });
        $('.dataTables_length').addClass('bs-select');
    });
</script>
<script>
$(document).ready(function () {
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var id = button.data('id') // Extract info from data-* attributes
        var employee = button.data('name') // Extract info from data-* attributes
        var delete_url = button.data('delete_url')
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this)
        modal.find('.modal-title').text('Delete User: ' + employee)
        modal.find('#employee-name').text(employee)
        $('#deactivate-form').attr('action',delete_url)
    });
});
</script>

@endpush

resources/views/backend/employees/shifts.blade.php
@extends('backend.layouts.main')

@section('content')
    <div>
        <h2> {{ $employee->name }}'s Default Shift </h2>
        
        <hr> 

        {{-- Current Shift --}}
        <h4> Current Shift</h4>
        <p> Click to remove shift from default </p>

        @if(sizeof($employee->shifts)>0)
            <div class="row row-cols-2 row-cols-lg-3 row-cols-xl-5">
                @foreach($employee->shifts as $shift)
                    <div class="col mb-4">
                        <form method="POST" action="{{ route('coreui.employee-shift.delete') }}">
                            {{ csrf_field() }}
                            <input type="hidden" name="employee" value="{{$employee->id}}">
                            <input type="hidden" name="shift" value="{{$shift->id}}">
                            <button class="btn" type="submit">
                                <div class="card text-center">
                                    <div class="card-body">
                                        <h5 class="card-title">{{$shift->day}}</h5>
                                        <p class="card-text">
                                            {{$shift->start_time}} - {{$shift->end_time}}
                                        </p>
                                    </div>
                                </div>
                            </button>
                        </form>
                    </div>
                @endforeach
            </div>
        @else
            <div class="alert alert-info text-center m-5 pt-4">
                <p>{{$employee->name}} currently have no default shifts</p>
            </div>
        @endif
           
        <hr>

        {{-- Adding shift --}}
        <h4> Add Shift </h4>

        <p> Click to add shift to default shift</p>
        <div class="row row-cols-2 row-cols-lg-3 row-cols-xl-5">
        @foreach( App\WorkShift::availableShift($employee->id)->get() as $shift)
            <div class="col mb-4">
                <form method="POST" action="{{ route('coreui.employee-shift.create') }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="employee" value="{{$employee->id}}">
                    <input type="hidden" name="shift" value="{{$shift->id}}">
                    <button class="btn" type="submit">
                        <div class="card text-center">
                            <div class="card-body">
                                <h5 class="card-title">{{$shift->day}}</h5>
                                <p class="card-text">
                                    {{$shift->start_time}} - {{$shift->end_time}}
                                </p>
                            </div>
                        </div>
                    </button>
                </form>
            </div>
        @endforeach
        </div>

    </div>
@endsection