routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

date_default_timezone_set('America/Vancouver');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('restricted', function () {
    return view('restricted');
})->name('restricted');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/toc', function(){
    return view('frontend.toc-datacore');
})->name('toc');

Route::get('/development', function(){
    return view('development');
})->name('development');

/////////////////////////////////////////////////////////////////////
// Backend
////////////////////////////////////////////////////////////////////
Route::prefix('/coreui')->name('coreui.')->group(function () {
    // Dashboard
    Route::get('/', 'HomeController@index')->name('dashboard');
    // Stats
    Route::get('statistics',function(){
        return view('backend.stats.index');
    })->name('stats')->middleware('auth')->middleware('permission:statistics.read');
    // Integrations
    Route::get('integrations',function(){
        return view('backend.integrations.index');
    })->name('integrations')->middleware('auth');

    Route::get('integrations/banner_message', 'IntegrationController@bannerIndex')->name('banner-message')->middleware('auth')->middleware('permission:banner.read');

    // Employees
    Route::get('/employees', 'EmployeeController@index')->name('employees')->middleware('permission:employee.read');
    Route::get('/employees/create', 'EmployeeController@create')->name('employees.create')->middleware('permission:employee.create');
    Route::post('/employees', 'EmployeeController@store')->name('employees.store')->middleware('permission:employee.create');
    Route::get('/employees/edit/{employee}', 'EmployeeController@edit')->name('employees.edit')->middleware('permission:employee.update');
    Route::patch('/employees/edit/{employee}', 'EmployeeController@update')->name('employees.update')->middleware('permission:employee.update');
    Route::patch('/employees/activate/{employee}', 'EmployeeController@activate')->name('employees.activate')->middleware('permission:employee.update');
    Route::patch('/employees/deactivate/{employee}', 'EmployeeController@deactivate')->name('employees.deactivate')->middleware('permission:employee.update');
    Route::get('/employees/delete/{employee}', 'EmployeeController@destroy')->name('employees.delete')->middleware('permission:employee.delete');
    Route::get('/employees/{employee}/shift','EmployeeController@shifts')->name('employees.shifts')->middleware('permission:employee.update');
    
    // Profile
    Route::get('/profile', 'EmployeeController@profile')->name('profile')->middleware('auth');
    Route::patch('/profile/{employee}', 'EmployeeController@profile_update')->name('profile.update')->middleware('auth');
    
    //Employee Permissions
    Route::get('/employees/{employee}/permissions', 'EmployeePermissionController@edit')->name('employee-permission.edit')->middleware('permission:employee.update');
    Route::patch('/employees/{employee}/permissions', 'EmployeePermissionController@update')->name('employee-permission.update')->middleware('permission:employee.update');

    // Employee Roles
    Route::get('/roles', 'EmployeeRoleController@index')->name('employee-role')->middleware('permission:employee_role.read');
    Route::post('/roles', 'EmployeeRoleController@store')->name('employee-role.store')->middleware('permission:employee_role.create');
    Route::post('/roles/{employee_role}', 'EmployeeRoleController@update')->name('employee-role.update')->middleware('permission:employee_role.update');

    // Employee Role Permissions
    Route::get('/roles/{employee_role}/permissions', 'EmployeeRolePermissionController@edit')->name('employee-role-permission.edit')->middleware('permission:employee_role.update');
    Route::patch('/roles/{employee_role}/permissions', 'EmployeeRolePermissionController@update')->name('employee-role-permission.update')->middleware('permission:employee_role.update');

    // Permissions
    Route::get('/permissions', 'PermissionController@index')->name('permission')->middleware('permission:permission.read')->middleware('role:SuperAdmin');
    Route::post('/permissions', 'PermissionController@store')->name('permission.store')->middleware('permission:permission.create')->middleware('role:SuperAdmin');

    // Sales History

    Route::get('/sales_history/index', 'SalesHistoryController@index')
    ->name('sales-history')->middleware('role:SuperAdmin')->middleware('permission:sales_history.read');

    Route::get('/sales_history/upload', 'SalesHistoryController@upload')
    ->name('sales-history.upload')->middleware('permission:sales_history.create');

    Route::post('/sales_history', 'SalesHistoryController@store')
    ->name('sales-history.store')->middleware('permission:sales_history.create');

    Route::get('/sales_history/{product}', 'SalesHistoryController@show')
    ->name('sales-history.show')->middleware('role:SuperAdmin')->middleware('permission:sales_history.read');

    // Vendors

    Route::get('/vendors/index', 'VendorController@index')
    ->name('vendors')->middleware('permission:vendors.read');

    Route::get('/vendors/{vendor}/products', 'VendorController@products')
    ->name('vendors.products')->middleware('permission:vendors.read');

    Route::get('/vendors/upload', 'VendorController@upload')
    ->name('vendors.upload')->middleware('role:SuperAdmin')->middleware('permission:vendors.create');

    Route::post('/vendors', 'VendorController@store')
    ->name('vendors.store')->middleware('role:SuperAdmin')->middleware('permission:vendors.create');

    // Purchase Orders

    Route::get('/purchases/index', 'PurchaseOrderController@index')
    ->name('po')->middleware('permission:purchase_orders.read');

    Route::get('/purchases/upload', 'PurchaseOrderController@upload')
    ->name('po.upload')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    Route::post('/purchases', 'PurchaseOrderController@store')
    ->name('po.store')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    Route::get('/purchases/{po_id}', 'PurchaseOrderController@products')
    ->name('po.products')->middleware('permission:purchase_orders.read');

    Route::get('/purchases/product/upload', 'PurchaseOrderProductController@upload')
    ->name('po-product.upload')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    Route::post('/purchase_products', 'PurchaseOrderProductController@store')
    ->name('po-product.store')->middleware('role:SuperAdmin')->middleware('permission:purchase_orders.update');

    // Payroll
    Route::get('/payroll-report', 'PayrollController@index')->name('payroll')->middleware('auth');

    // Work Shifts
    Route::get('/shifts','WorkShiftController@index')->name('work-shifts')->middleware('permission:work_shifts.read');

    // Employee Shift
    Route::post('employee/shift/add','WorkShiftController@addEmployeeShift')->name('employee-shift.create')->middleware('permission:work_shifts.create');
    Route::post('employee/shift/delete','WorkShiftController@removeEmployeeShift')->name('employee-shift.delete')->middleware('permission:work_shifts.delete');

    // Settings
    Route::get('settings',function(){
        return view('backend.settings.index');
    })->name('settings')->middleware('auth');

    // Order Statuses
    Route::get('/order_statuses','OrderStatusController@index')->name('order-status')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.read');
    Route::get('/order_statuses/create','OrderStatusController@create')->name('order-status.create')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.create');
    Route::post('/order_statuses','OrderStatusController@store')->name('order-status.store')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.create');
    Route::patch('/order_statuses/edit/{orderStatus}','OrderStatusController@update')->name('order-status.update')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.update');
    Route::get('/order_statuses/delete/{orderStatus}','OrderStatusController@destroy')->name('order-status.delete')->middleware('role:SuperAdmin,Supervisor')->middleware('permission:order_status.delete');

    // Events/Schedule
    Route::get('/schedule-vue','EventController@vue')->name('schedule-vue');
    Route::get('/schedule','EventController@index')->name('schedule');
    Route::get('/schedule-admin','EventController@admin')->name('schedule-admin')->middleware('permission:events.read');
    Route::get('/schedule-employee/{employee}','EventController@employee')->name('schedule-employee')->middleware('permission:events.read');
    Route::post('/schedule/create','EventController@create')->name('event.create');
    Route::patch('/schedule/update','EventController@update')->name('event.update');
    Route::post('/schedule/delete','EventController@destroy')->name('event.delete');


});

////////////////////////////////////////////////////////////////////////////
// Frontend
///////////////////////////////////////////////////////////////////////////

/**************************************************************
 * 
 *   Search
 * 
 ***************************************************************/ 

Route::get('/search', 'ProductController@search')->name('search');

app/Http/Controllers/IntegrationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class IntegrationController extends Controller
{
    public function bannerIndex(){
        return view('backend.integrations.website.banner-message');
    }

    public function bannerMessage(Request $request){
        Storage::disk('public')->put('banner_message.txt', $request->message_body);
   
        return back();
    }
}

resources/views/backend/integrations/index.blade.php
@extends('backend.layouts.main')

@section('content')
    <div class="container d-flex justify-content-center" style="height:80vh">
        <div class="my-auto text-center">
            <h5>WinPos Integrations/Tools</h5>
            
            @if(Auth::user()->hasAccess('sales_history')->create)
            <a href="{{route('coreui.sales-history.upload')}}"><button class="btn btn-primary">Import Monthly Sales</button></a> <br>
            @endif

            @if(Auth::user()->hasAccess('vendors')->create)
            <a href="{{route('coreui.vendors.upload')}}"><button class="btn btn-primary  mt-2">Import Vendors</button></a>
            <a href="{{route('vendors.update')}}"><button class="btn btn-primary  mt-2" onclick="openLoader()">Update Product Vendors</button></a> <br>
            @endif

            @if(Auth::user()->hasAccess('purchase_orders')->create)
            <a href="{{route('coreui.po.upload')}}"><button class="btn btn-primary  mt-2">Import Purchase Orders</button></a> <br>
            <a href="{{route('coreui.po-product.upload')}}"><button class="btn btn-primary  mt-2">Import Purchase Order Products</button></a><br>
            @endif

            @if(Auth::user()->hasAccess('cost')->update)
            <a href="{{route('vendors.update-recent-cost')}}"><button class="btn btn-primary  mt-2" onclick="openLoader()">Update Recent Cost for Vendors</button></a>
            <a href="{{route('vendors.update-avg-cost')}}"><button class="btn btn-primary  mt-2" onclick="openLoader()">Update Average Cost for Vendors</button></a>
            @endif

            @if(!Auth::user()->hasAccess('sales_history')->create && !Auth::user()->hasAccess('vendors')->create && !Auth::user()->hasAccess('purchase_orders')->create && !Auth::user()->hasAccess('cost')->update)
            <div class="alert alert-info">
                <p>You have no permissions for WinPos integrations</p>
            </div>
            @endif

            <hr>

            <h5>Prestashop Integrations/Tools</h5>
            @if(Auth::user()->hasAccess('category')->update)
            <a href="{{route('category.search')}}"><button class="btn btn-primary">Force Categories</button></a> <br>
            @endif
            @if(Auth::user()->hasAccess('brands')->update)
            <a href="{{route('brand.search')}}"><button class="btn btn-primary mt-2">Update Manufacturer/Brand</button></a> <br>
            @endif
            @if(Auth::user()->hasAccess('banner')->update)
            <a href="{{route('coreui.banner-message')}}"><button class="btn btn-primary mt-2">Update Banner Message</button></a><br>
            @endif

            @if(Auth::user()->hasAccess('product')->update)
            <a href="{{ route("online-product.syncDescription") }}"><button class="btn btn-primary mt-2" onclick="openLoader()">Sync All Product Description</button><br>
            <a href="{{ route("online-product.syncShortDescription") }}"><button class="btn btn-primary mt-2" onclick="openLoader()">Sync All Product Short Description</button><br>
            @endif

            @if(!Auth::user()->hasAccess('category')->update && !Auth::user()->hasAccess('brands')->update && !Auth::user()->hasAccess('banner')->update)
            <div class="alert alert-info">
                <p>You have no permissions for prestashop integrations</p>
            </div>
            @endif

            {{-- <hr/> --}}
            
            
            {{-- <h5>Convert Comments from FS to DC</h5>
            @if(Auth::user()->hasRole('SuperAdmin')) --}}
            {{-- <h5>Convert Comments from FS to DC</h5>
            @if(Auth::user()->hasRole('SuperAdmin')) --}}
            {{-- <form method="POST" action="{{route('notes.missing-convert')}}" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" onclick="openLoader()">Convert Missing Notes</button>
                </div>
            </form>

            <form method="POST" action="{{route('notes.relation-convert')}}" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary"  onclick="openLoader()">Convert Relation Notes to General</button>
                </div>
            </form>

            <form method="POST" action="{{route('notes.obsolete-convert')}}" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Convert Obsolete Notes</button>
                </div>
            </form> --}}

            <form method="POST" action="{{route('price-changes-update')}}" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary mt-2" onclick="openLoader()">Update Price Change Table</button>
                </div>
            </form>

            {{-- @else
            <div class="alert alert-info">
                    <p>You have must be an Admin in order to convert. <br>Please contact support if transfer is required.</p>
                </div>
            @endif --}}

        </div>
    </div>

@endsection

@push('bottom-scripts')

<script>
    function openLoader(){
        $('#loader').toggle();
    }
</script>

@endpush